# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('descript', models.CharField(blank=True, max_length=200, null=True)),
                ('picture', models.ImageField(blank=True, upload_to='')),
                ('file', models.FileField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Новости',
                'verbose_name': 'Новость',
            },
        ),
    ]
