# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20170218_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='descript',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
