# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20170218_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='picture',
        ),
    ]
