# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_remove_doc_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='news',
        ),
    ]
